apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- injector-deployment.yaml
- injector-mutating-webhook.yaml
- injector-rbac.yaml
- injector-service.yaml
- injector-leader-extras.yaml
